name: azureml_py36
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cudatoolkit==10.1.243
  - fbprophet==0.5
  - pytorch==1.4.0
  - py-xgboost<=0.90
  - setuptools-git>=1.2
  - pip:
    - adal<2.0.0,>=0.4.5,>=0.6.0,>=1.2.0
    - ansiwrap==0.8.4
    - azure-common~=1.1,>=1.1.12
    - azure-graphrbac>=0.40.0
    - azure-identity<1.3.0,>=1.2.0
    - azure-mgmt-authorization>=0.40.0
    - azure-mgmt-containerregistry>=2.0.0
    - azure-mgmt-keyvault>=0.40.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-resource<9.0.0,>=1.2.1
    - azure-mgmt-storage>=1.5.0
    - azureml-accel-models~=1.2.0
    - azureml-automl-core~=1.2.0
    - azureml-automl-runtime~=1.2.0
    - azureml-cli-common~=1.2.0
    - azureml-contrib-notebook~=1.2.0
    - azureml-core~=1.2.0
    - azureml-datadrift~=1.2.0
    - azureml-dataprep<1.4.0a,>=1.3.5
    - azureml-dataprep-native<15.0.0,>=14.1.0
    - azureml-defaults~=1.2.0
    - azureml-explain-model~=1.2.0
